// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/go-eagle/eagle-layout/internal/server"
	"github.com/go-eagle/eagle/pkg/app"
)

// Injectors from wire.go:

func InitApp(cfg *app.Config, config *app.ServerConfig) (*app.App, error) {
	rabbitmqServer := server.NewRabbitMQServer()
	appApp := newApp(cfg, rabbitmqServer)
	return appApp, nil
}
