// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/go-eagle/eagle-layout/internal/server"
	"github.com/go-eagle/eagle-layout/internal/tasks"
	"github.com/go-eagle/eagle/pkg/app"
)

// Injectors from wire.go:

func InitApp(cfg *app.Config, config *app.ServerConfig, tc *tasks.Config) (*app.App, func(), error) {
	redisServer := server.NewConsumerServer(tc)
	appApp := newApp(cfg, redisServer)
	return appApp, func() {
	}, nil
}
