// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/go-eagle/eagle-layout/internal/tasks"

	"github.com/go-eagle/eagle-layout/internal/server"
	"github.com/go-eagle/eagle-layout/internal/service"
	"github.com/go-eagle/eagle/pkg/app"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func InitApp(cfg *tasks.Config, config *app.ServerConfig) (*app.App, error) {
	greeterService := service.NewGreeterService()
	grpcServer := server.NewGRPCServer(config, greeterService)
	appApp := newApp(cfg, grpcServer)
	return appApp, nil
}
