// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/go-eagle/eagle-layout/internal/server"
	"github.com/go-eagle/eagle-layout/internal/service"
	"github.com/go-eagle/eagle-layout/internal/tasks"
	"github.com/go-eagle/eagle/pkg/app"
)

// Injectors from wire.go:

func InitApp(cfg *app.Config, config *app.ServerConfig, taskCfg *tasks.Config) (*app.App, error) {
	cronJobService := service.NewCronJobService()
	cronjobServer := server.NewCronJobServer(taskCfg, cronJobService)
	appApp := newApp(cfg, cronjobServer)
	return appApp, nil
}
