// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"github.com/go-eagle/eagle-layout/internal/dal/db/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.UserInfoModel{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.UserInfoModel{}) fail: %s", err)
	}
}

func Test_userInfoModelQuery(t *testing.T) {
	userInfoModel := newUserInfoModel(_gen_test_db)
	userInfoModel = *userInfoModel.As(userInfoModel.TableName())
	_do := userInfoModel.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(userInfoModel.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <user_info> fail:", err)
		return
	}

	_, ok := userInfoModel.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from userInfoModel success")
	}

	err = _do.Create(&model.UserInfoModel{})
	if err != nil {
		t.Error("create item in table <user_info> fail:", err)
	}

	err = _do.Save(&model.UserInfoModel{})
	if err != nil {
		t.Error("create item in table <user_info> fail:", err)
	}

	err = _do.CreateInBatches([]*model.UserInfoModel{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <user_info> fail:", err)
	}

	_, err = _do.Select(userInfoModel.ALL).Take()
	if err != nil {
		t.Error("Take() on table <user_info> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <user_info> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <user_info> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <user_info> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.UserInfoModel{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <user_info> fail:", err)
	}

	_, err = _do.Select(userInfoModel.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <user_info> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <user_info> fail:", err)
	}

	_, err = _do.Select(userInfoModel.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <user_info> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <user_info> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <user_info> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <user_info> fail:", err)
	}

	_, err = _do.ScanByPage(&model.UserInfoModel{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <user_info> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <user_info> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <user_info> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <user_info> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <user_info> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <user_info> fail:", err)
	}
}

var UserInfoModelGetUserByUsernameTestCase = []TestCase{}

func Test_userInfoModel_GetUserByUsername(t *testing.T) {
	userInfoModel := newUserInfoModel(_gen_test_db)
	do := userInfoModel.WithContext(context.Background()).Debug()

	for i, tt := range UserInfoModelGetUserByUsernameTestCase {
		t.Run("GetUserByUsername_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.GetUserByUsername(tt.Input.Args[0].(string))
			assert(t, "GetUserByUsername", res1, tt.Expectation.Ret[0])
			assert(t, "GetUserByUsername", res2, tt.Expectation.Ret[1])
		})
	}
}

var UserInfoModelGetUserByPhoneTestCase = []TestCase{}

func Test_userInfoModel_GetUserByPhone(t *testing.T) {
	userInfoModel := newUserInfoModel(_gen_test_db)
	do := userInfoModel.WithContext(context.Background()).Debug()

	for i, tt := range UserInfoModelGetUserByPhoneTestCase {
		t.Run("GetUserByPhone_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.GetUserByPhone(tt.Input.Args[0].(string))
			assert(t, "GetUserByPhone", res1, tt.Expectation.Ret[0])
			assert(t, "GetUserByPhone", res2, tt.Expectation.Ret[1])
		})
	}
}

var UserInfoModelGetUserByEmailTestCase = []TestCase{}

func Test_userInfoModel_GetUserByEmail(t *testing.T) {
	userInfoModel := newUserInfoModel(_gen_test_db)
	do := userInfoModel.WithContext(context.Background()).Debug()

	for i, tt := range UserInfoModelGetUserByEmailTestCase {
		t.Run("GetUserByEmail_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.GetUserByEmail(tt.Input.Args[0].(string))
			assert(t, "GetUserByEmail", res1, tt.Expectation.Ret[0])
			assert(t, "GetUserByEmail", res2, tt.Expectation.Ret[1])
		})
	}
}
