// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-eagle/eagle-layout/internal/server"
	"github.com/go-eagle/eagle-layout/internal/service"
	"github.com/go-eagle/eagle/pkg/app"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func InitApp(cfg *app.Config, config *app.ServerConfig) (*app.App, func(), error) {
	greeterService := service.NewGreeterService()
	grpcServer := server.NewGRPCServer(config, greeterService)
	appApp := newApp(cfg, grpcServer)
	return appApp, func() {
	}, nil
}
